/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyCameleon {
    }
    interface MyMover {
    }
    interface MyOrbit {
    }
}
declare global {
    interface HTMLMyCameleonElement extends Components.MyCameleon, HTMLStencilElement {
    }
    var HTMLMyCameleonElement: {
        prototype: HTMLMyCameleonElement;
        new (): HTMLMyCameleonElement;
    };
    interface HTMLMyMoverElement extends Components.MyMover, HTMLStencilElement {
    }
    var HTMLMyMoverElement: {
        prototype: HTMLMyMoverElement;
        new (): HTMLMyMoverElement;
    };
    interface HTMLMyOrbitElement extends Components.MyOrbit, HTMLStencilElement {
    }
    var HTMLMyOrbitElement: {
        prototype: HTMLMyOrbitElement;
        new (): HTMLMyOrbitElement;
    };
    interface HTMLElementTagNameMap {
        "my-cameleon": HTMLMyCameleonElement;
        "my-mover": HTMLMyMoverElement;
        "my-orbit": HTMLMyOrbitElement;
    }
}
declare namespace LocalJSX {
    interface MyCameleon {
    }
    interface MyMover {
    }
    interface MyOrbit {
    }
    interface IntrinsicElements {
        "my-cameleon": MyCameleon;
        "my-mover": MyMover;
        "my-orbit": MyOrbit;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-cameleon": LocalJSX.MyCameleon & JSXBase.HTMLAttributes<HTMLMyCameleonElement>;
            "my-mover": LocalJSX.MyMover & JSXBase.HTMLAttributes<HTMLMyMoverElement>;
            "my-orbit": LocalJSX.MyOrbit & JSXBase.HTMLAttributes<HTMLMyOrbitElement>;
        }
    }
}
